"""initial migration

Revision ID: 001
Revises:
Create Date: 2026-04-07 16:56:26.616618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('repo_filter', sa.String(length=500), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=True),
    sa.Column('total_checked', sa.Integer(), nullable=True),
    sa.Column('total_resolved', sa.Integer(), nullable=True),
    sa.Column('total_updated', sa.Integer(), nullable=True),
    sa.Column('total_skipped', sa.Integer(), nullable=True),
    sa.Column('total_errors', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_actions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('run_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('snyk_issue_id', sa.String(length=200), nullable=False),
    sa.Column('jira_key', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_actions')
    op.drop_table('sync_runs')
    # ### end Alembic commands ###

